### ISSUE TITLE
Implement more Tree Metrics

### ISSUE THREAD

**Issue by gordonkoehn** [cbg-ethz/PYggdrasil#107]
In the dawn of the first experiments to come and the Ancestor-Descendant similarity being undefined for some cases, I propose to implement another metric. 

I looked through the other `scphylo` metrics for quick-to-implement distances. The most promising candidate seems to be the  

[Multi-labeled tree dissimilarity measure (MLTD)](https://almob.biomedcentral.com/articles/10.1186/s13015-019-0152-9)

It is described as: 

> Given two clonal trees, our multi-labelled tree dissimilarity (MLTD) measure is defined as the minimum number of mutation/label deletions, (empty) leaf deletions, and vertex (clonal) expansions, applied in any order, to convert each of the two trees to the maximum common
tree. We show that the MLTD measure can be computed efficiently in polynomial time and it captures the similarity between trees of different clonal granularity well.

As the ideal metric for us would be the MCMC SCITE distance - whilst intractable - this seems to go in the same direction.

Other candidates would be:
- [CASet distance](https://academic.oup.com/bioinformatics/article/36/7/2090/5637226?login=true):  puts more weight on the internal old nodes
- [DISC distance](https://academic.oup.com/bioinformatics/article/36/7/2090/5637226?login=true): puts more weight on the leaves

Big thanks to @laurabquintas for the expert judgement in the distance metrics!

**Comment by gordonkoehn** [comment]
@pawel-czyz What do you think ? - definitely a medium priority for now.

**Comment by pawel-czyz** [comment]
Thanks Gordon and Laura! I think there are good ideas and it'd be good to have more metrics. But let's see what the initial experiments tell us and then we'll decide what to prioritise next.

**Comment by gordonkoehn** [comment]
Similar issue, more specific:
- #119
