### ISSUE TITLE
Full MCMC simulation

### ISSUE THREAD

**Issue by pawel-czyz** [cbg-ethz/PYggdrasil#20]
For a given set of error rates, initial tree, and seed, and cell data, collect the samples and save them to the disk.

In sprint #18

**Comment by pawel-czyz** [comment]
Time estimates: M, L.

**Comment by gordonkoehn** [comment]
Raise value error if nan or homozygous mutation matrix is given.

**Comment by gordonkoehn** [comment]
Add proper formating for runtime and runtime for sample.

**Comment by gordonkoehn** [comment]
Change default read data to `perfect_mutation_mat`

**Comment by gordonkoehn** [comment]
- [ ] consider using `xarray.save_mfdataset` instead of `json` to write mcmc samples.

**Comment by gordonkoehn** [comment]
- [ ] print config file to log.
