### ISSUE TITLE
Tree visualisation

### ISSUE THREAD

**Issue by pawel-czyz** [cbg-ethz/PYggdrasil#21]
For a given tree, save an image with it rendered with log-prob in the title.

Sprint: #18

**Comment by gordonkoehn** [comment]
Defining the Product: 

plotTree(Args): that takes a tree and print options to save a report grade visualisation.

Args: 
	- TreeNode or root of Tree
		- Name:  title of the tree (title of the Tree given by the root name root)
		- Data: dict(of arguments to print, on each node)
	- print options
		- print title: name of the root
		- print tree_data :  dict( strings of argument of data to print)
		- print nodes print data : dict(strings of arguments of data to print)
	- save name
	- save dir

This implementation will use the GraphViz tools. Dark blue solid nodes with white labels are imagined. 

[TreeVisualization_Product_2023-04-24.pdf](https://github.com/cbg-ethz/PYggdrasil/files/11309007/TreeVisualization_Product_2023-04-24.pdf)

**Comment by gordonkoehn** [comment]
Dropping the feature to `print node_data` other than the root. 

Reason: no obvious reason for this project. - no facial implementation.
