### ISSUE TITLE
Visualisation of time series

### ISSUE THREAD

**Issue by pawel-czyz** [cbg-ethz/PYggdrasil#23]
Time estimates: M and M.

Part of sprint #18

**Comment by gordonkoehn** [comment]
The actual 2D platting is easy matplotlib -  gathering the data from the saved trees with log-likelihood (and perhaps calculating the distances) is the larger part. 

It might be better to do the #20 first.

**Comment by pawel-czyz** [comment]
> The actual 2D platting is easy matplotlib - gathering the data from the saved trees with log-likelihood (and perhaps calculating the distances) is the larger part.
> 
> It might be better to do the #20 first.

Good point, I have similar intuition :slightly_smiling_face:
(And it also depends on #22 , which I'll probably do on Friday)

**Comment by gordonkoehn** [comment]
- [ ] The plot with X axis being iteration number, Y axis being the loglikelihood of the sampled tree.
- [ ] The number of iterations needed to sample the true tree.
- [ ] Plot of the distance to the true tree on the Y axis for several chains and the iteration number on X axis.

**Comment by gordonkoehn** [comment]
**Objectives:**

Planned to happen in 3 smaller PRs. 
- []

**Comment by gordonkoehn** [comment]
First PR to implement Objective 2,3 submitted for review. #38

**Comment by gordonkoehn** [comment]
On cold until #48  is resolved.

**Comment by gordonkoehn** [comment]
Current Early State:

![Image](https://github.com/cbg-ethz/PYggdrasil/assets/10867778/e457c3b0-e6d0-488d-894b-6ce01ac479f8)

Still missing:

- [ ] has true tree been reached
- [ ] plot the most likely and starting / true tree
