### ISSUE TITLE
Setting the simulations

### ISSUE THREAD

**Issue by pawel-czyz** [cbg-ethz/PYggdrasil#24]
(As described in the sprint description #18 ).

Time estimates: 
  - Initial: S and XL.
  - Revised: XL and XL.

**Comment by gordonkoehn** [comment]
Experimental outline:

10, 50, 100 mutations, 
ERROR RATES: 
EASY : FNR: 0.097, FPR: 1.24e-06, 
HARD : FNR: 0.2,  FPR: 0.05
			“High error rates LEAD TO DIFFUSE POSTERIOR”
na false
homozygous false
Cells: 1000

mcmc samples: 12000
initial tree: Huntress, Broad, Deep 5, Random 5, True
move probabilities: Standard SCITE

**Comment by gordonkoehn** [comment]
Additional overhead: Euler slurm
