### ISSUE TITLE
Consistent naming of FNR and FPR

### ISSUE THREAD

**Issue by pawel-czyz** [cbg-ethz/PYggdrasil#30]
In the original SCITE paper $\alpha$ stands for FPR (false positive rate) and $\beta$ stands for FNR (false negative rate).

However, in the cell simulation script the notation is reversed:

```python
    parser.add_argument("--alpha", required=True, help="False negative rate", type=float)
    parser.add_argument("--beta", required=True, help="False positive rate", type=float)
```
It'd be good to go through the code and see whether the naming is consistent. I'd also perhaps suggest to drop $\alpha$ and $\beta$ notation entirely and use `fpr` and `fnr` instead.

**Comment by gordonkoehn** [comment]
Time Estimate: S

**Comment by gordonkoehn** [comment]
The correct notation as in the SCITE paper is: 

alpha = $\alpha$ = False Positive Rate  = FPR
beta = $\beta$ = False Negative Rate = FNR
