### ISSUE TITLE
Make sure we follow one convention of mutation matrices

### ISSUE THREAD

**Issue by pawel-czyz** [cbg-ethz/PYggdrasil#31]
The public API should support only one matrix format. Currently we have them somewhat mixed.

####  `(n_cells, n_mutations)`
  - In this format each cell has its own row and sequenced sites are in different columns.
  - This is easy to make work with scPhylo. (And arguably easier to parse using Pandas).
  - Two files (e.g., from two different sequencing runs, but with the same genes) are easy to concatenate just with `cat`.

#### `(n_mutations, n_cells)`
  - In this format each cell has its own rows and sequenced sites are in different columns.
  - It seems that this is the input format of [SCITE](https://github.com/cbg-ethz/SCITE).

**Comment by gordonkoehn** [comment]
Also, consider wheater to truncate the last mutation/root row in the mutation matrix. As in the description in `tree_inference.interface` it is all one: "Every cell carries the mutation/site of the root" - not physically meaningful. In the SCITE paper this is truncated. See a worked example here  
[Mutation_Matrix_LastRow-2023-05-04.pdf](https://github.com/cbg-ethz/PYggdrasil/files/11394920/Mutation_Matrix_LastRow-2023-05-04.pdf)

@pawel-czyz shall I truncate it?

**Comment by pawel-czyz** [comment]
> As per our doubt yesterday - the full mutation matrix has the last row all ones, corresponding to the root
> 
> We should consider wheater to truncate the last mutation/root row in the mutation matrix. As in the description in `tree_inference.interface` it is all one: "Every cell carries the mutation/site of the root" - not physically meaningful. In the SCITE paper this is truncated. See a worked example here [Mutation_Matrix_LastRow-2023-05-04.pdf](https://github.com/cbg-ethz/PYggdrasil/files/11394920/Mutation_Matrix_LastRow-2023-05-04.pdf)
> 
> @pawel-czyz shall I truncate it?

Good point! I think the "mutation matrix" should be what is stands for: we have a set of cells and some of them are carrying mutations.
It's possible that the augmented matrix with additional ones is helpful enough so that it deserves its own class (e.g., `_AugmentedMutationMatrix`), but I don't think it should be a central object passed around or available in public API.

**Comment by gordonkoehn** [comment]
Time Estimate: M

**Comment by gordonkoehn** [comment]
Choosing `MutationMatrix :(n_mutations, n_cells)`as in the SCITE paper, but keep the `AncestoryMatrix : (n_mutations+1,n_mutations+1)`
