### ISSUE TITLE
🏃 Sprint 2: First Experiment

### ISSUE THREAD

**Issue by pawel-czyz** [cbg-ethz/PYggdrasil#32]
This scopes the second sprint, lasting three weeks (**May 10th – May 31st**).

---

  - How much does HUNTRESS initialization help, compared to "broad one", "deep one", random?
  - (How robust is HUNTRESS to bootstrap?)
  - How quickly do different chains converge?
  - How do different moves influence mixing speed?
  - How do the landscapes look like for different FPR, FNR (and possibly missing rate?)

---
As a reader of your thesis, I'd like to see:

  -  The plot with X axis being iteration number, Y axis being the loglikelihood of the sampled tree.
  - The number of iterations needed to sample the true tree.
  - Plot of the distance to the true tree on the Y axis for several chains and the iteration number on X axis.

We want to have this:
  - For FP and FN rates taken from SCITE simulation paper (probably 1% and 10%, but I don't remember) and 5, 10, 30, 50. mutations and 15,000 steps $\times$ 4 chains. 
  - For a misspecified model, where the true rates are slightly larger that the specified ones to the model used in the MCMC inference. (Example: rather than having 1% and 10% error rates as given to the MCMC SCITE model, we simulate the data from the 2%, 15%).

**Comment by gordonkoehn** [comment]
Done.
