### ISSUE TITLE
Ponder about Estimating Probabilities with Missing Data

### ISSUE THREAD

**Issue by gordonkoehn** [cbg-ethz/PYggdrasil#34]
This task is an exercise in probability, to get used to modelling at missing data.

## Warm-up

Consider a coin you just got. You tossed it three times, got $(0, 1, 0)$ and you would like to see whether it is biased.

The likelihood can be described in terms of the following generative model:
$$X_i \mid p \sim \mathrm{Bernoulli}(p)$$
with $(X_1, \dotsc, X_3) = (0, 1, 0)$.

  - [x] How does the likelihood $L(p)$ look like? Is it concentrated around some value? Flat?

## Missing data: a naive approach

Previously we observed *all* coin tosses. Imagine now that you tried to toss the coin three times, but the third time you tossed it, it fell from the table on the floor and you didn't see the result.

In other words, you saw $(0, 1, \text{NaN})$.

  - [x] How would you intuitively model likelihood $L(p)$ in this case?
  - [x] Can you see an assumption you made here?

## Missing completely at random

Imagine now that Mr. Odin is tossing the coin three times. However, whenever he tosses a coin, he also throws a six-sided dice. If he sees 1, he *will not* reveal the result to you.

In other words, the generative model is now:
$X_i \mid p \sim \mathrm{Bernoulli}(p)$
$Y_i \sim \mathrm{Categorical}(1/6, 1/6, \dotsc, 1/6)$
$$(E_i \mid X_i, Y_i) =  X_i\ \text{ if } Y_i \neq 1\ \text{ else }  \text{NaN}$$

You observed $(E_1, E_2, E_3) = (0, 1, \text{NaN})$. 

  - [x] What is the likelihood $L(p)$?

## Other types of missing data

Now Mr. Loki is tossing the coin three times and he will again use (a fair) dice. However, he wants to cheat you: whenever he sees 1, he will try to underreport it. He is using the following model:
 
$X_i \mid p \sim \mathrm{Bernoulli}(p)$
$Y_i \sim \mathrm{Categorical}(1/6, 1/6, \dotsc, 1/6)$
$$(E_i \mid X_i, Y_i) =  \text{NaN  if }  \bigg((X_i=1 \text{ and } Y_i \le 3) \text{ or } (X_i=0 \text{ and } Y_i=1)\bigg) \text{ else }X_i.$$ 

  - [x] You were told the answers $(0, 1, \text{NaN})$. How does the likelihood $L(p)$ look like in this case?
  - [x] Take a look at Section 1.1 and Section 1.2 of [this book](https://stefvanbuuren.name/fimd/sec-problem.html).

**Comment by gordonkoehn** [comment]
Finished working through all your prompts - thanks for structuring this learning so well! - Enjoyed this quest. 

See my workings on this branch here: 
[gordon/ponder-na-probs Notebook](https://github.com/cbg-ethz/PYggdrasil/blob/gordon/ponder-na-probs/notebooks/ponder-na-probs.ipynb)

Please let me know if this is what you had in mind / if is correct.

Read the intro of the book - great resource. Something, I aim to learn more about.

**Comment by pawel-czyz** [comment]
Hi Gordon!

Nice work! Some perspectives:

### Warm-up
- The expression for likelihood is right. As you can see, for e.g., 100 coin tosses the numbers would be so close to 0 that it wouldn't be possible to keep them in  `float` – and this is the most important reason why we usually work with **log**likelihoods
- While $1/3$ is the MLE estimate, the likelihood isn't really that concentrated. I like to think about in this way: if we use flat prior $\mathrm{Beta}(1, 1)$, the likelihood is the posterior here. And there are multiple values (the whole region between, say, 0.1 and 0.8) which are compatible with the data collected. If we had more data, we would be able to have a sharper likelihood.

### Missing data: a naive approach

Indeed! And I think this is exactly what we will do in SCITE with missing data.

### Missing completely at random

Likelihood functions $L(p)$ and $a\cdot L(p)$ for $a>0$ yield the same results when used in MLE or Bayesian inference, so it doesn't really matter, but I got a different constant:
$$L(p) = P(E_1=0\mid p) P(E_2=1\mid p) P(E_3=\mathrm{NaN}\mid p).$$

$P(E_1=0\mid p) = (1-p)\cdot 5/6$, $P(E_2=1\mid p) = p\cdot 5/6$, $P(E_3\mid p) = 1/6$.

Then MLE is indeed at $p=1/2$ (there's a small typo in the notebook) and the profile is still very diffuse (two coin tosses are not many :sweat_smile:).

### Other types of missing data
I haven't actually done the maths, so I don't know the final formula, but this how to do it:
$$P(E_1=0\mid p) = \sum_{x=0}^{1} \sum_{y=1}^{6) P(E_1 = 0\mid X_1=x, Y_1=y) P(X_1=x\mid p) P(Y_1=y)$$

**Comment by gordonkoehn** [comment]
Ah, thank you for the perspective and hint! - worked through the maths and I think I got it, the shape of likelihood makes sense. 

$P(E_1 = 0 | p) = \frac{5}{6} (1-p)$
$P(E_2=1 | p) = \frac{1}{2}$
$P(E_3=NaN | p) = \frac{1}{6} (1-p) + \frac{p}{2}$

Thank you for the formalism ! - Looking forward to the next theory quest !
