### ISSUE TITLE
Revise MCMC Script

### ISSUE THREAD

**Issue by gordonkoehn** [cbg-ethz/PYggdrasil#66]
Resise the `run_mcmc.py` script to 
- [x] use the new file naming of #54
- [x] use trees generated by #61 
- [x] #69

Ideally, done after 
- #23 
is done, to keep PRs small Some changes in `run_mcmc.py`

**Comment by gordonkoehn** [comment]
Regarding removing the MCMC run config file -  @pawel-czyz may I run this setup by you.

- create a `pydantic` model for the  MCMC run configs - import the ones that already exist in `pyggdrasil` 
- set te `pydantic` models in the snakemake 
- pass the models as a dict - i.e. serialisable to a the shell running the python script

This allows me to use a `pydantic` to check the configurations as well as keeping the code to run a mcmc simulation in a script -  as it contains a lot of logging and file handeling better to keep outside of `pyggdrasil`.

So effectively I am proposing a snakemake as this: 

```
import json
from pydantic import BaseModel
from snakemake import shell

### import from pyggdrasil
# Define a Pydantic model
class MoveProbs(BaseModel):
    prune_and_reattach: float
    swap_node_labels: float
    swap_subtrees: float

class Config(BaseModel):
    move_probs: MoveProbs
    fnr: float
    fpr: float
    num_samples: int
    burn_in: int
    thinning: int
####

# Set the Model
# Create an instance of the Pydantic model with hardcoded values
config = Config(
    move_probs=MoveProbs(
        prune_and_reattach=0.1,
        swap_node_labels=0.65,
        swap_subtrees=0.25
    ),
    fnr=0.097,
    fpr=1.24e-06,
    num_samples=100,
    burn_in=10,
    thinning=2
)

rule my_rule:
    output:
        "output.txt"
    shell:
        "python my_script.py {output} {params.config_dict_json}"
    
params:
    config_dict_json=json.dumps(config.dict())
```

**Comment by pawel-czyz** [comment]
Hi Gordon,

This should work!

An alternative:

```
from cool_package import run_some_function
...

CONFIGS = {
   "realistic_config": Config(
    move_probs=MoveProbs(
        prune_and_reattach=0.1,
        swap_node_labels=0.65,
        swap_subtrees=0.25
    ),
    fnr=0.097,
    fpr=1.24e-06,
    num_samples=100,
    burn_in=10,
    thinning=2
)

rule all:
   input: expand("output-{scenario}.txt", scenario=CONFIGS.keys())

rule my_rule:
    output:
        "output-{scenario}.txt"
    run:
        config = CONFIGS[str(wildcards.scenario)]
        run_some_function(config, desired_output = str(output))
```

**Comment by gordonkoehn** [comment]
Yes, that's elegant. Thank you for the alternative will implement one of the above very soon,
