### ISSUE TITLE
MARK02 - Convergence issues

### ISSUE THREAD

**Issue by gordonkoehn** [cbg-ethz/PYggdrasil#76]
## Subtasks
- [x] #94
- [x] #95
- [x] #96

## Description Product
For different FPR, FNR, number of cells and mutations:
True tree
4 chains, with different initializations
10,000 steps
Take 5,000 latest trees (i.e., ignore these from the (suspected) “warm up/burnin” period)
Visualise e.g., the distance from the true tree to different trees

![Image](https://github.com/cbg-ethz/PYggdrasil/assets/10867778/396225e7-97d4-46fb-afd1-2f39f64bfb45)

x-axis: some distance from true tree

y-axis: coloured histograms of different chains

Outcome: indication of multimodality or not, does the algorith work

**Comment by gordonkoehn** [comment]
@pawel-czyz 

What shall our true tree be here - again a random one? - Do we run chains of different initial trees or different initial random seeds but the same initial tree ? - What do we define as the initialization here ? 

I'd say we take different random trees.

**Comment by pawel-czyz** [comment]
For one true tree we have one generated data set and then we can run several chains (from different starting points) and see if they mix properly (i.e., they forget about the starting point).

Of course, running the whole fitting procedure for different true trees also makes sense, to understand better whether a particular simulation (e.g., chains not converging) is somewhat typical behaviour or just some very random fluctuation.

**Comment by gordonkoehn** [comment]
Thank you for the prompt reply.

Alright, I'll just make a random tree for the initial tree and again random trees as the different starting points.
