### ISSUE TITLE
Add Snakemake Format Checker

### ISSUE THREAD

**Issue by gordonkoehn** [cbg-ethz/PYggdrasil#81]
@pawel-czyz Have you ever used `snakefmt` ? 

I am enjoying `black` very much for automatic formation and was looking to have the same for snakemake files. 
This package seems to do it and be quite popular.
https://pypi.org/project/snakefmt/

What do you say ?  Shall we try to integrate in pre-commit and github actions ?

**Comment by pawel-czyz** [comment]
I haven't used it yet, but it sounds good to me! I'd however suggest to wait with this issue until we're happy with initial experiments.

**Comment by gordonkoehn** [comment]
Yes, it's low priority for sure. Will do it when there is time to spare.
